version: '3.8'

# back-end variables
x-common-variables:
  &common-backend-variables
  ENV: PROD
  USER_URL: http://user:8000
  MATCHING_URL: http://matching:8001
  CODING_URL: http://coding:8002
  VIDEO_URL: http://video:8003
  QUESTION_URL: http://question:8004
  HISTORY_URL: http://history:8005

services:
  gateway:
    container_name: gateway
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
    volumes:
      - ./gateway:/home/node/app/gateway
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      <<: *common-backend-variables
      HTTP_PROXY: 'http://localhost:8080'

  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/home/node/app/frontend
    ports:
      - 3000:3000
    restart: on-failure

  user:
    container_name: user
    build:
      dockerfile: Dockerfile
      context: ./user-service
    volumes:
      - ./user-service:/home/node/app/user-service
    expose:
      - 8000
    restart: on-failure
    environment:
      <<: *common-backend-variables
      DB_CLOUD_URI: 'mongodb+srv://cs3219-g15:cs3219-g15@cs3219-g15.ryvsrmt.mongodb.net/?retryWrites=true&w=majority'

  matching:
    container_name: matching
    build:
      dockerfile: Dockerfile
      context: ./matching-service
    volumes:
      - ./matching-service:/home/node/app/matching
    expose:
      - 8001
    restart: on-failure
    environment:
      <<: *common-backend-variables

  coding:
    container_name: coding
    build:
      dockerfile: Dockerfile
      context: ./coding-service
    volumes:
      - ./coding-service:/home/node/app/coding-service
    expose:
      - 8002
    restart: on-failure
    environment:
      <<: *common-backend-variables

  question:
    container_name: question
    build:
      dockerfile: Dockerfile
      context: ./question-service
    volumes:
      - ./question-service:/home/node/app/question_service
    expose:
      - 8004
    restart: on-failure
    environment:
      <<: *common-backend-variables
      DATABASE_USERNAME: cs3219g15
      DATABASE_PASSWORD: Password1234!
      DATABASE_HOST: question-service.mysql.database.azure.com
  
  history:
    container_name: history
    build:
      dockerfile: Dockerfile
      context: ./history-service
    volumes:
      - ./history-service:/home/node/app/history_service
    expose:
      - 8005
    restart: on-failure
    environment:
      <<: *common-backend-variables
      DB_CLOUD_URI: 'mongodb+srv://cs3219-history:cs3219-history@cs3219-history.u9n8v5t.mongodb.net/?retryWrites=true&w=majority'

volumes: 
  question-service:
  coding-service:
  matching-service: 
  user-service:
  frontend:
  gateway:

  # Used for local dev
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   restart: always
