apiVersion: v1
kind: ConfigMap
metadata:
  name: peerprep-config
  namespace: default
data:
  ENV: PROD
  MATCHING_URL: http://matching:8001
  USER_URL: http://user:8000
  CODING_URL: http://user:8002
  QUESTION_URL: http://question:8004
  HISTORY_URL: http://history:8005
