name: Add opened issues and PRs to project

# Controls when the workflow will run
on:
  # Triggers on opened issues
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/CS3219-AY2223S1/projects/30/views/8
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
